version: '3.1'
services:

  db:
    image: postgres:12
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwedsazxc
      - POSTGRES_USER=app
    ports:
      - "5432:5432"

  eureka:
    image: dc.sidgroup.pl/s4t-eureka:1.0.8
    ports:
      - "8761:8761"

  dict:
    image: lapierre/dictionary-service:0.0.1
    environment:
      - DICT_DATASOURCE_HOST=db:5432
      - DICT_DATASOURCE_PASSWORD=qwedsazxc
      - DICT_DATASOURCE_USER=app
    ports:
      - "9098:9098"

volumes:
  pg_data: